DROP TABLE IF EXISTS[dbo].[CASE/OFFENSE]
DROP TABLE IF EXISTS[dbo].[OFFENSE]
DROP TABLE IF EXISTS[dbo].[OFFENSE_CATEGORY]
DROP TABLE IF EXISTS[dbo].[INCARCERATION]
DROP TABLE IF EXISTS[dbo].[HEARING]
DROP TABLE IF EXISTS[dbo].[CASE]
DROP TABLE IF EXISTS[dbo].[PRISON]
DROP TABLE IF EXISTS[dbo].[RELEASE_STATUS]
DROP TABLE IF EXISTS[dbo].[COURT]
DROP TABLE IF EXISTS[dbo].[CASE_STATUS]
DROP TABLE IF EXISTS[dbo].[ATTORNEY]
DROP TABLE IF EXISTS[dbo].[PRISONER]
DROP TABLE IF EXISTS[dbo].[LEGAL_FIRM]

CREATE TABLE [dbo].[PRISONER]
(
	[PrisonerID] [nvarchar](15) NOT NULL,
	[PrisonerFirstName] [nvarchar](20) NOT NULL,
	[PrisonerLastName] [nvarchar](50) NOT NULL,
	[PrisonerMiddleName] [nvarchar](20) NOT NULL,
	[PrisonerAddress] [nvarchar](50) NOT NULL,
	[PrisonerSSN] [char](9) NOT NULL,
	[PrisonerAge] int NOT NULL,
 CONSTRAINT [PK_PRISONER] PRIMARY KEY CLUSTERED 
(
	[PrisonerID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRISON]
(
	[PrisonID] [nvarchar](15) NOT NULL,
	[PrisonName] [nvarchar](50) NOT NULL,
	[PrisonState] [nvarchar](7) NOT NULL,
	[PrisonCity] [nvarchar](20) NOT NULL,
	[PrisonAddress] [nvarchar](50) NOT NULL,
	[PrisonZipCode] [char](5) NOT NULL,
 CONSTRAINT [PK_PRISON] PRIMARY KEY CLUSTERED 
(
	[PrisonID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[LEGAL_FIRM]
(
	[LegalFirmID] [nvarchar](15) NOT NULL,
	[LegalFirmName] [nvarchar](50) NOT NULL,
	[LegalFirmState] [nvarchar](7) NOT NULL,
	[LegalFirmCity] [nvarchar](20) NOT NULL,
	[LegalFirmAddress] [nvarchar](50) NOT NULL,
	[LegalFirmZipCode] [char](5) NOT NULL,
 CONSTRAINT [PK_LEGAL_FIRM] PRIMARY KEY CLUSTERED 
(
	[LegalFirmID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[RELEASE_STATUS]
(
	[ReleaseStatusID] [char](10) NOT NULL,
	[ReleaseStatusDescription] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_RELEASE_STATUS] PRIMARY KEY CLUSTERED 
(
	[ReleaseStatusID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[CASE_STATUS]
(
	[CaseStatusID] [nvarchar](15) NOT NULL,
	[CaseStatusDescription] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CASE_STATUS] PRIMARY KEY CLUSTERED 
(
	[CaseStatusID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[COURT]
(
	[CourtID] [nvarchar](15) NOT NULL,
	[CourtName] [nvarchar](50) NOT NULL,
	[CourtState] [nvarchar](7) NOT NULL,
	[CourtCity] [nvarchar](20) NOT NULL,
	[CourtAddress] [nvarchar](50) NOT NULL,
	[CourtZipCode] [char](5) NOT NULL,
 CONSTRAINT [PK_COURT] PRIMARY KEY CLUSTERED 
(
	[CourtID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[OFFENSE_CATEGORY]
(
	[OffenseCategoryID] [nvarchar](15) NOT NULL,
	[OffenseCategoryDescription] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_OFFENSE_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[OffenseCategoryID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[OFFENSE]
(
	[OffenseID] [nvarchar](15) NOT NULL,
	[OffenseDescription] [nvarchar](50) NOT NULL,
	[OffenseCategoryID] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_OFFENSE] PRIMARY KEY CLUSTERED 
(
	[OffenseID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE [dbo].[OFFENSE]  WITH CHECK 
ADD CONSTRAINT [FK_OFFENSE_OFFENSE_CATEGORY] FOREIGN KEY([OffenseCategoryID])
REFERENCES [dbo].[OFFENSE_CATEGORY] ([OffenseCategoryID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[OFFENSE] CHECK CONSTRAINT [FK_OFFENSE_OFFENSE_CATEGORY]
GO

CREATE TABLE [dbo].[ATTORNEY]
(
	[AttorneyID] [nvarchar](15) NOT NULL,
	[AttorneyFirstName] [nvarchar](20) NOT NULL,
	[AttorneyLastName] [nvarchar](20) NOT NULL,
	[AttorneyMiddleName] [nvarchar](20) NOT NULL,
	[LegalFirmID] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_ATTORNEY] PRIMARY KEY CLUSTERED 
(
	[AttorneyID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ATTORNEY]  WITH CHECK 
ADD CONSTRAINT [FK_ATTORNEY_LEGAL_FIRM] FOREIGN KEY([LegalFirmID])
REFERENCES [dbo].[LEGAL_FIRM] ([LegalFirmID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[ATTORNEY] CHECK CONSTRAINT [FK_ATTORNEY_LEGAL_FIRM]
GO

CREATE TABLE [dbo].[CASE]
(
	[CaseID] [nvarchar](15) NOT NULL,
	[CaseStatusID] [nvarchar](15) NOT NULL,
	[PrisonerID] [nvarchar](15) NOT NULL,
	[AttorneyID] [nvarchar](15) NOT NULL,	
 CONSTRAINT [PK_CASE] PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CASE]  WITH CHECK 
ADD CONSTRAINT [FK_CASE_CASE_STATUS] FOREIGN KEY([CaseStatusID])
REFERENCES [dbo].[CASE_STATUS] ([CaseStatusID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[CASE]  WITH CHECK 
ADD CONSTRAINT [FK_CASE_PRISONER] FOREIGN KEY([PrisonerID])
REFERENCES [dbo].[PRISONER] ([PrisonerID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[CASE]  WITH CHECK 
ADD CONSTRAINT [FK_CASE_ATTORNEY] FOREIGN KEY([AttorneyID])
REFERENCES [dbo].[ATTORNEY] ([AttorneyID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[CASE] CHECK CONSTRAINT [FK_CASE_CASE_STATUS]
GO

ALTER TABLE [dbo].[CASE] CHECK CONSTRAINT [FK_CASE_PRISONER]
GO

ALTER TABLE [dbo].[CASE] CHECK CONSTRAINT [FK_CASE_ATTORNEY]
GO


CREATE TABLE [dbo].[HEARING]
(
	[HearingID] [nvarchar](15) NOT NULL,
	[HearingDate] [nvarchar](20) NOT NULL,
	[HearingTime] [nvarchar](20) NOT NULL,
	[CourtID] [nvarchar](15) NOT NULL,	
	[CaseID] [nvarchar](15) NOT NULL,
  CONSTRAINT [PK_HEARING] PRIMARY KEY CLUSTERED 
(
	[HearingID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE [dbo].[HEARING]  WITH CHECK 
ADD CONSTRAINT [FK_HEARING_COURT] FOREIGN KEY([CourtID])
REFERENCES [dbo].[COURT] ([CourtID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[HEARING]  WITH CHECK 
ADD CONSTRAINT [FK_HEARING_CASE] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE] ([CaseID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[HEARING] CHECK CONSTRAINT [FK_HEARING_COURT]
GO

ALTER TABLE [dbo].[HEARING] CHECK CONSTRAINT [FK_HEARING_CASE]
GO

CREATE TABLE [dbo].[INCARCERATION]
(
	[IncarcerationID] [nvarchar](15) NOT NULL,
	[AdmittedDate] [char](10) NOT NULL,
	[ReleasedDate] [char](10) NOT NULL,
	[ReleaseStatusID] [char](10) NOT NULL,
	[PrisonID] [nvarchar](15) NOT NULL,
	[CaseID] [nvarchar](15) NOT NULL,
  CONSTRAINT [PK_INCARCERATION] PRIMARY KEY CLUSTERED 
(
	[IncarcerationID] ASC
)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE [dbo].[INCARCERATION]  WITH CHECK 
ADD CONSTRAINT [FK_INCARCERATION_RELEASE_STATUS] FOREIGN KEY([ReleaseStatusID])
REFERENCES [dbo].[RELEASE_STATUS] ([ReleaseStatusID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[INCARCERATION]  WITH CHECK 
ADD CONSTRAINT [FK_INCARCERATION_PRISON] FOREIGN KEY([PrisonID])
REFERENCES [dbo].[PRISON] ([PrisonID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[INCARCERATION]  WITH CHECK 
ADD CONSTRAINT [FK_INCARCERATION_CASE] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE] ([CaseID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[INCARCERATION] CHECK CONSTRAINT [FK_INCARCERATION_RELEASE_STATUS]
GO

ALTER TABLE [dbo].[INCARCERATION] CHECK CONSTRAINT [FK_INCARCERATION_PRISON]
GO

ALTER TABLE [dbo].[INCARCERATION] CHECK CONSTRAINT [FK_INCARCERATION_CASE]
GO

CREATE TABLE [dbo].[CASE/OFFENSE]
(
	[CaseID] [nvarchar](15) NOT NULL,
	[OffenseID] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_CASE/OFFENSE] PRIMARY KEY
(
	[CaseID] ASC,
	[OffenseID] ASC

)

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CASE/OFFENSE]  WITH CHECK 
ADD CONSTRAINT [FK_CASE/OFFENSE_CASE] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE] ([CaseID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[CASE/OFFENSE]  WITH CHECK 
ADD CONSTRAINT [FK_CASE/OFFENSE_OFFENSE] FOREIGN KEY([OffenseID])
REFERENCES [dbo].[OFFENSE] ([OffenseID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[CASE/OFFENSE] CHECK CONSTRAINT [FK_CASE/OFFENSE_CASE]
GO

ALTER TABLE [dbo].[CASE/OFFENSE] CHECK CONSTRAINT [FK_CASE/OFFENSE_OFFENSE]
GO
